# サンプル
# https://gist.github.com/Shougo/3d2adcb83e9eb0e8d4af
# https://github.com/Shougo/shougo-s-github/blob/master/vim/rc/neobundle.toml

[[plugins]]
repository = 'scrooloose/syntastic'
insert = 1
[[plugins]]
repository = 'Shougo/neocomplcache'
insert = 1
[[plugins]]
repository = 'yuratomo/w3m.vim'
  [plugins.autoload]
  commands = [ 'W3m', 'W3mHistory', 'W3mHistoryClear', 'W3mLocal', 'W3mSplit', 'W3mTab', 'W3mVSplit' ]
[[plugins]]
repository = 'mattn/benchvimrc-vim'
  [plugins.autoload]
  commands = [ 'BenchVimrc' ]
[[plugins]]
repository = 'mattn/emoji-vim'
  [plugins.autoload]
  commands = [ 'Emoji' ]
[[plugins]]
repository = 'glidenote/octoeditor.vim'
  [plugins.autoload]
  commands = [ 'OctopressNew', 'OctopressList', 'OctopressGrep' ]
[[plugins]]
repository = 'koron/codic-vim'
  [plugins.autoload]
  commands = [ 'Codic' ]

# filetype
[[plugins]]
repository = 'cespare/vim-toml'
  [plugins.autoload]
  filetypes = [ 'toml' ]
[[plugins]]
repository = 'slim-template/vim-slim'
  [plugins.autoload]
  filetypes = [ 'slim' ]
[[plugins]]
repository = 'vim-scripts/applescript.vim'
  [plugins.autoload]
  filetypes = [ 'scpt', 'applescript' ]
[[plugins]]
repository = 'othree/html5.vim'
  [plugins.autoload]
  filetypes = [ 'html' ]
[[plugins]]
repository = 'kchmck/vim-coffee-script'
  [plugins.autoload]
  filetypes = [ 'coffee' ]
[[plugins]]
repository = 'xsbeats/vim-blade'
  [plugins.autoload]
  filetypes = [ 'blade' ]
[[plugins]]
repository = 'jelera/vim-javascript-syntax'
  [plugins.autoload]
  filetypes = [ 'javascript' ]
[[plugins]]
repository = 'rhysd/vim-clang-format'
  [plugins.autoload]
  filetypes = [ 'c', 'cpp', 'objc', 'pch' ]

[[plugins]] # OctopressGit.vim
repository = 'https://gist.github.com/6775207.git'
script_type = 'plugin'
  [plugins.autoload]
  commands = [ 'OctopressGit' ]
