# サンプル
# https://gist.github.com/Shougo/3d2adcb83e9eb0e8d4af
[[plugins]]
repository = 'Shougo/vimproc.vim'
  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin = 'make -f make_cygwin.mak'
  mac = 'make -f make_mac.mak'
  unix = 'make -f make_unix.mak'

# 便利系
[[plugins]]
repository = 'osyo-manga/vim-itunes-bgm'
repository = 'lambdalisue/vim-gista'
depends = [ 'tyru/open-browser.vim' ]
#repository = 'justinmk/vim-dirvish'
[[plugins]]
repository = 'scrooloose/nerdtree'
[[plugins]]
repository = 'jistr/vim-nerdtree-tabs'
