# サンプル
# https://gist.github.com/Shougo/3d2adcb83e9eb0e8d4af
# https://github.com/Shougo/shougo-s-github/blob/master/vim/rc/neobundle.toml

[[plugins]]
repository = 'soramugi/nerdtree'
  [plugins.autoload]
  commands = [ 'NERDTree', 'NERDTreeClose', 'NERDTreeToggle', 'NERDTreeFromBookmark' ]
  explorer = 1
[[plugins]]
repository = 'scrooloose/syntastic'
insert = 1
[[plugins]]
repository = 'Shougo/neocomplcache'
insert = 1
[[plugins]]
repository = 'L9'
insert = 1
[[plugins]]
repository = 'FuzzyFinder'
depends = 'L9'
insert = 1
[[plugins]]
repository = 'yuratomo/w3m.vim'
  [plugins.autoload]
  commands = [ 'W3m', 'W3mHistory', 'W3mHistoryClear', 'W3mLocal', 'W3mSplit', 'W3mTab', 'W3mVSplit' ]
[[plugins]]
repository = 'mattn/benchvimrc-vim'
  [plugins.autoload]
  commands = [ 'BenchVimrc' ]
[[plugins]]
repository = 'soramugi/pocket.vim'
  [plugins.autoload]
  commands = [ 'PocketList' ]
[[plugins]]
repository = 'mattn/emoji-vim'
  [plugins.autoload]
  commands = [ 'Emoji' ]
[[plugins]]
repository = 'glidenote/octoeditor.vim'
  [plugins.autoload]
  commands = [ 'OctopressNew', 'OctopressList', 'OctopressGrep' ]
[[plugins]]
repository = 'koron/codic-vim'
  [plugins.autoload]
  commands = [ 'Codic' ]

# filetype
[[plugins]]
repository = 'cespare/vim-toml'
  [plugins.autoload]
  filetypes = [ 'toml' ]
[[plugins]]
repository = 'slim-template/vim-slim'
  [plugins.autoload]
  filetypes = [ 'slim' ]
[[plugins]]
repository = 'vim-scripts/applescript.vim'
  [plugins.autoload]
  filetypes = [ 'scpt', 'applescript' ]
[[plugins]]
repository = 'othree/html5.vim'
  [plugins.autoload]
  filetypes = [ 'html' ]
[[plugins]]
repository = 'kchmck/vim-coffee-script'
  [plugins.autoload]
  filetypes = [ 'coffee' ]


[[plugins]] # OctopressGit.vim
repository = 'https://gist.github.com/6775207.git'
script_type = 'plugin'
  [plugins.autoload]
  commands = [ 'OctopressGit' ]
[[plugins]] # tumblrからランダムで画像リンクの出力
repository = 'https://gist.github.com/4f6d95e05827018f2318.git'
script_type = 'plugin'
  [plugins.autoload]
  commands = [ 'Linktotag' ]
